# -*- coding: utf-8 -*-
"""Final Project - Data processing Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTINQs1t70hti63mP2BI76qd80cuX8Sk
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import transforms, datasets
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch.nn.functional as F
import matplotlib.pyplot as plt

import datetime
import os

import time
from pathlib import Path

from tqdm import tqdm

!pip install thop

!pip install torchinfo

seed = 42
np.random.seed(seed)
torch.manual_seed(seed)

if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

"""# **DataSet Loader**"""

from google.colab import drive
drive.mount('/content/drive')

BASE_DIR = Path('/content/drive/MyDrive/creep_data')
# For a local Python project, use something like:
# BASE_DIR = Path(__file__).resolve().parent / "creep_data"

# For a local notebook:
#BASE_DIR = Path.cwd() / "creep_data"
primary_data_folder = BASE_DIR / "01_primary_data"
all_dfs = []

# Contains metadata for type of material, liquid the material was immersed in, final time to failure and elongation
secondary_data_folder = BASE_DIR / "02_secondary_data" / "FNCT_secondary_data.csv"
metadata_df = pd.read_csv(secondary_data_folder, sep=";", skiprows=[1], encoding="latin1")

# Strip whitespace from column names in metadata_df
metadata_df.columns = metadata_df.columns.str.strip()

metadata_file = secondary_data_folder

processed_data_folder = BASE_DIR / "processed_data"

seed = 42
sequence_length = 10
forecast_horizon = 1

measurement_columns = [
    "Duration",
    "Force",
    "Elongation",
    "Temperature"
]

target_feature = "Elongation"

# Loads all primary creep-test CSV files, converts measurement
# columns to numeric values, assigns a unique Case_ID to each
# experiment, and combines all of them into one DataFrame.

def load_primary_data(
    primary_data_folder,
    measurement_columns
):
    all_dfs = []

    csv_files = sorted(
        primary_data_folder.glob("*.csv")
    )

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV files found in: {primary_data_folder}"
        )

    for csv_file in csv_files:
        print(f"Preprocessing: {csv_file.name}")

        df = pd.read_csv(
            csv_file,
            sep=";",
            skiprows=[1],
            encoding="utf-8-sig"
        )

        # Remove accidental spaces from column names
        df.columns = df.columns.str.strip()

        missing_columns = [
            column
            for column in measurement_columns
            if column not in df.columns
        ]

        if missing_columns:
            raise ValueError(
                f"{csv_file.name} is missing columns: "
                f"{missing_columns}"
            )

        # Convert only measurement columns to numeric
        df[measurement_columns] = (
            df[measurement_columns]
            .apply(
                pd.to_numeric,
                errors="coerce"
            )
        )

        # One CSV file represents one experimental case
        df["Case_ID"] = csv_file.stem.strip()

        all_dfs.append(df)

    combined_df = pd.concat(
        all_dfs,
        ignore_index=True
    )

    print(
        f"\nLoaded {combined_df['Case_ID'].nunique()} cases."
    )

    print(
        f"Total primary-data rows: {len(combined_df)}"
    )

    return combined_df

# Loads the secondary metadata file, separates the final
# prediction labels from the remaining metadata features

def load_metadata(metadata_file):
    metadata_df = pd.read_csv(
        metadata_file,
        sep=";",
        skiprows=[1],
        encoding="latin1"
    )

    # Remove leading or trailing spaces from headers
    metadata_df.columns = (
        metadata_df.columns.str.strip()
    )

    label_columns = [
        "Time to failure tf",
        "Final elongation d"
    ]

    required_columns = [
        "Process_ID"
    ] + label_columns

    missing_columns = [
        column
        for column in required_columns
        if column not in metadata_df.columns
    ]

    if missing_columns:
        raise ValueError(
            "Metadata is missing required columns: "
            f"{missing_columns}"
        )

    # Clean metadata identifiers before splitting or merging
    metadata_df["Process_ID"] = (
        metadata_df["Process_ID"]
        .astype(str)
        .str.strip()
    )

    # Final case-level labels remain separate
    label_df = metadata_df[
        ["Process_ID"] + label_columns
    ].copy()

    # Remove final outcomes from model features
    metadata_features = metadata_df.drop(
        columns=label_columns
    ).copy()

    return metadata_features, label_df

# Merges the experiment-level metadata with the primary
# time-series measurements using Case_ID

def merge_metadata(
    combined_df,
    metadata_features
):
    combined_df = combined_df.copy()
    metadata_features = metadata_features.copy()

    combined_df["Case_ID"] = (
        combined_df["Case_ID"]
        .astype(str)
        .str.strip()
    )

    metadata_features["Process_ID"] = (
        metadata_features["Process_ID"]
        .astype(str)
        .str.strip()
    )

    duplicate_process_ids = (
        metadata_features["Process_ID"]
        .duplicated()
        .sum()
    )

    if duplicate_process_ids > 0:
        raise ValueError(
            "Metadata contains duplicate Process_ID values: "
            f"{duplicate_process_ids}"
        )

    rows_before_merge = len(combined_df)

    print(
        "\nPrimary-data columns before merge:",
        combined_df.columns.tolist()
    )

    print(
        "\nMetadata columns before merge:",
        metadata_features.columns.tolist()
    )

    combined_df = combined_df.merge(
        metadata_features,
        left_on="Case_ID",
        right_on="Process_ID",
        how="left",
        validate="many_to_one",
        suffixes=("_primary", "_metadata")
    )

    rows_after_merge = len(combined_df)

    print(
        "\nCombined columns after merge:",
        combined_df.columns.tolist()
    )

    print(
        "\nRows before and after merge:",
        rows_before_merge,
        "->",
        rows_after_merge
    )

    if rows_before_merge != rows_after_merge:
        raise ValueError(
            "Metadata merge changed the number of rows."
        )

    unmatched_cases = combined_df.loc[
        combined_df["Process_ID"].isna(),
        "Case_ID"
    ].unique()

    print("\nCases that failed to match metadata:")
    print(unmatched_cases)

    if len(unmatched_cases) > 0:
        print(
            "Warning: Some primary cases have no matching metadata."
        )

    sanity_columns = [
        "material",
        "Medium",
        "Stress nominal ?n"
    ]

    existing_sanity_columns = [
        column
        for column in sanity_columns
        if column in combined_df.columns
    ]

    if existing_sanity_columns:
        print(
            "\nMaximum unique metadata values per case:"
        )

        print(
            combined_df
            .groupby("Case_ID")[existing_sanity_columns]
            .nunique()
            .max()
        )

    return combined_df

# Removes rows containing missing measurement values and sorts
# each experiment chronologically
def clean_data(
    combined_df,
    measurement_columns
):
    combined_df = combined_df.copy()

    missing_counts = (
        combined_df[measurement_columns]
        .isna()
        .sum()
    )

    print(
        "\nMissing values before cleaning:"
    )
    print(missing_counts)

    rows_before = len(combined_df)

    combined_df = combined_df.dropna(
        subset=measurement_columns
    ).reset_index(drop=True)

    rows_removed = rows_before - len(combined_df)

    print(
        f"\nRows removed because of missing "
        f"measurements: {rows_removed}"
    )

    combined_df = (
        combined_df
        .sort_values(
            ["Case_ID", measurement_columns[0]]
        )
        .reset_index(drop=True)
    )

    return combined_df

# Splits the dataset into training, validation, and testing
# sets

def split_by_case(
    combined_df,
    test_size=0.30,
    validation_fraction=0.50,
    seed=42
):
    unique_cases = (
        combined_df["Case_ID"]
        .dropna()
        .unique()
    )

    if len(unique_cases) < 3:
        raise ValueError(
            "At least three unique cases are required "
            "for train, validation, and test splits."
        )

    train_cases, temp_cases = train_test_split(
        unique_cases,
        test_size=test_size,
        random_state=seed
    )

    val_cases, test_cases = train_test_split(
        temp_cases,
        test_size=validation_fraction,
        random_state=seed
    )

    train_df = combined_df[
        combined_df["Case_ID"].isin(train_cases)
    ].copy()

    val_df = combined_df[
        combined_df["Case_ID"].isin(val_cases)
    ].copy()

    test_df = combined_df[
        combined_df["Case_ID"].isin(test_cases)
    ].copy()

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)

    case_splits = {
        "train": train_cases,
        "validation": val_cases,
        "test": test_cases
    }

    print("\nCase split:")
    print(f"Training cases: {len(train_cases)}")
    print(f"Validation cases: {len(val_cases)}")
    print(f"Test cases: {len(test_cases)}")

    print("\nRow counts:")
    print(f"Train: {train_df.shape}")
    print(f"Validation: {val_df.shape}")
    print(f"Test: {test_df.shape}")

    # Moved from check_case_overlap()
    train_ids = set(train_df["Case_ID"].unique())
    val_ids = set(val_df["Case_ID"].unique())
    test_ids = set(test_df["Case_ID"].unique())

    assert train_ids.isdisjoint(val_ids), (
        "Train and validation cases overlap."
    )

    assert train_ids.isdisjoint(test_ids), (
        "Train and test cases overlap."
    )

    assert val_ids.isdisjoint(test_ids), (
        "Validation and test cases overlap."
    )
    print(
        "\nNo case overlap detected between splits."
    )

    return (
        train_df,
        val_df,
        test_df,
        case_splits
    )

# Fits a StandardScaler using only the training data and
# applies the learned scaling parameters to the training,
# validation, and testing datasets.

def scale_features(
    train_df,
    val_df,
    test_df,
    features_to_scale
):
    scaler = StandardScaler()

    # Fit only on training data
    scaler.fit(
        train_df[features_to_scale]
    )

    train_scaled = train_df.copy()
    val_scaled = val_df.copy()
    test_scaled = test_df.copy()

    train_scaled[features_to_scale] = (
        scaler.transform(
            train_df[features_to_scale]
        )
    )

    val_scaled[features_to_scale] = (
        scaler.transform(
            val_df[features_to_scale]
        )
    )

    test_scaled[features_to_scale] = (
        scaler.transform(
            test_df[features_to_scale]
        )
    )

    print(
        "\nMean of scaled training features:"
    )
    print(
        train_scaled[
            features_to_scale
        ].mean()
    )

    print(
        "\nStandard deviation of scaled training features:"
    )
    print(
        train_scaled[
            features_to_scale
        ].std()
    )

    return (
        train_scaled,
        val_scaled,
        test_scaled,
        scaler
    )

# Generates fixed-length sliding-window sequences for each
# experiment independently

def create_sequences(
    df,
    sequence_length,
    forecast_horizon,
    input_features,
    target_feature,
    duration_feature
):
    X = []
    y = []
    sequence_case_ids = []

    for case_id in df["Case_ID"].unique():

        # Never allow a sequence to cross between cases
        case_df = (
            df[df["Case_ID"] == case_id]
            .sort_values(duration_feature)
            .reset_index(drop=True)
        )

        feature_data = (
            case_df[input_features]
            .to_numpy(dtype=np.float32)
        )

        target_data = (
            case_df[target_feature]
            .to_numpy(dtype=np.float32)
        )

        required_rows = (
            sequence_length
            + forecast_horizon
        )

        if len(case_df) < required_rows:
            print(
                f"Skipping {case_id}: "
                f"{len(case_df)} rows available, "
                f"but {required_rows} are required."
            )
            continue

        number_of_sequences = (
            len(case_df)
            - required_rows
            + 1
        )

        for start_index in range(
            number_of_sequences
        ):
            input_end = (
                start_index
                + sequence_length
            )

            target_end = (
                input_end
                + forecast_horizon
            )

            X_window = feature_data[
                start_index:input_end
            ]

            y_window = target_data[
                input_end:target_end
            ]

            X.append(X_window)
            y.append(y_window)
            sequence_case_ids.append(case_id)

    if not X:
        empty_X = torch.empty(
            (
                0,
                sequence_length,
                len(input_features)
            ),
            dtype=torch.float32
        )

        empty_y = torch.empty(
            (
                0,
                forecast_horizon
            ),
            dtype=torch.float32
        )

        return (
            empty_X,
            empty_y,
            sequence_case_ids
        )

    X_tensor = torch.tensor(
        np.asarray(X),
        dtype=torch.float32
    )

    y_tensor = torch.tensor(
        np.asarray(y),
        dtype=torch.float32
    )

    return (
        X_tensor,
        y_tensor,
        sequence_case_ids
    )

# Creates training, validation, and testing sequence tensors

def create_all_sequences(
    train_df,
    val_df,
    test_df,
    sequence_length,
    forecast_horizon,
    input_features,
    target_feature,
    duration_feature
):
    (
        X_train,
        y_train,
        train_sequence_case_ids
    ) = create_sequences(
        train_df,
        sequence_length,
        forecast_horizon,
        input_features,
        target_feature,
        duration_feature
    )

    (
        X_val,
        y_val,
        val_sequence_case_ids
    ) = create_sequences(
        val_df,
        sequence_length,
        forecast_horizon,
        input_features,
        target_feature,
        duration_feature
    )

    (
        X_test,
        y_test,
        test_sequence_case_ids
    ) = create_sequences(
        test_df,
        sequence_length,
        forecast_horizon,
        input_features,
        target_feature,
        duration_feature
    )

    sequence_data = {
        "X_train": X_train,
        "y_train": y_train,
        "X_val": X_val,
        "y_val": y_val,
        "X_test": X_test,
        "y_test": y_test
    }

    sequence_case_ids = {
        "train_sequence_case_ids":
            train_sequence_case_ids,
        "val_sequence_case_ids":
            val_sequence_case_ids,
        "test_sequence_case_ids":
            test_sequence_case_ids
    }

    print("\nSequence shapes:")

    for name, tensor in sequence_data.items():
        print(f"{name}: {tensor.shape}")

    return sequence_data, sequence_case_ids

# Splits the final experiment-level labels into training,
# validation, and testing sets using the same Case_ID split
# as the time-series data

def split_labels_by_case(
    label_df,
    case_splits
):
    label_df = label_df.copy()

    label_df["Process_ID"] = (
        label_df["Process_ID"]
        .astype(str)
        .str.strip()
    )

    train_labels = label_df[
        label_df["Process_ID"].isin(
            case_splits["train"]
        )
    ].copy()

    val_labels = label_df[
        label_df["Process_ID"].isin(
            case_splits["validation"]
        )
    ].copy()

    test_labels = label_df[
        label_df["Process_ID"].isin(
            case_splits["test"]
        )
    ].copy()

    label_splits = {
        "train_labels": train_labels,
        "val_labels": val_labels,
        "test_labels": test_labels
    }

    print("\nCase-level label counts:")
    print(f"Train: {len(train_labels)}")
    print(f"Validation: {len(val_labels)}")
    print(f"Test: {len(test_labels)}")

    return label_splits

def save_processed_data(
    sequence_data,
    sequence_case_ids,
    label_splits,
    output_folder
):
    output_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    # Save sequence tensors
    for name, tensor in sequence_data.items():
        torch.save(
            tensor,
            output_folder / f"{name}.pt"
        )

    # Save case IDs associated with each sequence
    for name, case_ids in sequence_case_ids.items():
        torch.save(
            case_ids,
            output_folder / f"{name}.pt"
        )

    # Save final case-level labels
    for name, dataframe in label_splits.items():
        dataframe.to_csv(
            output_folder / f"{name}.csv",
            index=False
        )

    print(
        f"\nProcessed data saved to: "
        f"{output_folder.resolve()}"
    )

def preprocess_data():
    # Load primary time-series data
    combined_df = load_primary_data(
        primary_data_folder,
        measurement_columns
    )

    # Load metadata and final labels
    metadata_features, label_df = load_metadata(
        metadata_file
    )

    # Merge safe metadata features
    combined_df = merge_metadata(
        combined_df,
        metadata_features
    )

    # Determine whether merging renamed any measurement columns
    column_mapping = resolve_measurement_columns(
        combined_df,
        measurement_columns
    )

    features_to_scale = [
        column_mapping["Duration"],
        column_mapping["Force"],
        column_mapping["Elongation"],
        column_mapping["Temperature"]
    ]

    resolved_target_feature = (
        column_mapping[target_feature]
    )

    duration_feature = (
        column_mapping["Duration"]
    )

    # Remove unusable measurement rows
    combined_df = clean_data(
        combined_df,
        features_to_scale
    )

    # Split complete cases
    (
        train_df,
        val_df,
        test_df,
        case_splits
    ) = split_by_case(
        combined_df,
        seed=seed
    )

    # Scale using training statistics only
    (
        train_scaled,
        val_scaled,
        test_scaled,
        scaler
    ) = scale_features(
        train_df,
        val_df,
        test_df,
        features_to_scale
    )

    # Create fixed-length windows inside each case
    (
        sequence_data,
        sequence_case_ids
    ) = create_all_sequences(
        train_scaled,
        val_scaled,
        test_scaled,
        sequence_length=sequence_length,
        forecast_horizon=forecast_horizon,
        input_features=features_to_scale,
        target_feature=resolved_target_feature,
        duration_feature=duration_feature
    )

    # Keep final outcome labels aligned to the same case split
    label_splits = split_labels_by_case(
        label_df,
        case_splits
    )

    # Save tensors, sequence case IDs, and final labels
    save_processed_data(
        sequence_data,
        sequence_case_ids,
        label_splits,
        processed_data_folder
    )

    return {
        "combined_df": combined_df,
        "train_df": train_df,
        "val_df": val_df,
        "test_df": test_df,
        "train_scaled": train_scaled,
        "val_scaled": val_scaled,
        "test_scaled": test_scaled,
        "sequence_data": sequence_data,
        "sequence_case_ids": sequence_case_ids,
        "label_splits": label_splits,
        "case_splits": case_splits,
        "scaler": scaler,
        "column_mapping": column_mapping
    }


results = preprocess_data()