# -*- coding: utf-8 -*-
"""training/testing_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-u1HUaONhBslDWUvbpjmArP_k5bZAfhF
"""

import copy
import torch
import torch.nn as nn

# TRAINING


def train_model(
    model,
    train_loader,
    val_loader,
    num_epochs=100,
    lr=1e-3,
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    early_stopping_patience=10,
    verbose=True,
):
    """
    Trains the model and checks its validation loss after each epoch.

    The model with the lowest validation loss is saved.
    Training stops early if validation loss does not improve for several epochs.

    Returns:
        model: trained model using the best saved weights
        history: training and validation loss for each epoch
    """
    model.to(device)

    # Mean squared error loss for regression
    criterion = nn.MSELoss()

    # Adam updates the model weights
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # Store loss values for plotting later
    history = {"train_loss": [], "val_loss": []}

    # Keep track of the best validation result
    best_val_loss = float("inf")
    best_state = copy.deepcopy(model.state_dict())
    epochs_without_improvement = 0

    for epoch in range(num_epochs):
        # Put the model in training mode
        model.train()
        running_loss = 0.0

        for X_batch, y_batch in train_loader:
            # Move the batch to the CPU or GPU
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            # Clear old gradients
            optimizer.zero_grad()

            # Make predictions
            preds = model(X_batch)

            # Calculate loss
            loss = criterion(preds, y_batch)

            # Calculate gradients
            loss.backward()

            # Update model weights
            optimizer.step()

            # Add this batch's total loss
            running_loss += loss.item() * X_batch.size(0)

        # Average training loss for the full dataset
        train_loss = running_loss / len(train_loader.dataset)

        # Calculate validation loss
        val_loss = evaluate_loss(model, val_loader, criterion, device)

        # Save loss values
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)

        # Print progress
        if verbose:
            print(
                f"Epoch {epoch + 1}/{num_epochs} - "
                f"train_loss: {train_loss:.4f} - "
                f"val_loss: {val_loss:.4f}"
            )

        # Save the model if validation loss improved
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = copy.deepcopy(model.state_dict())
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

            # Stop if validation loss has not improved
            if (
                early_stopping_patience is not None
                and epochs_without_improvement >= early_stopping_patience
            ):
                if verbose:
                    print(
                        f"Early stopping at epoch {epoch + 1} "
                        f"(no improvement for "
                        f"{early_stopping_patience} epochs)."
                    )
                break

    # Restore the best model weights
    model.load_state_dict(best_state)

    return model, history


def evaluate_loss(model, loader, criterion, device="cpu"):
    """Returns the average loss without training the model."""

    # Put the model in evaluation mode
    model.eval()
    running_loss = 0.0

    # Gradients are not needed during evaluation
    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            preds = model(X_batch)

            # Add this batch's total loss
            running_loss += (
                criterion(preds, y_batch).item() * X_batch.size(0)
            )

    # Return the average loss for all samples
    return running_loss / len(loader.dataset)



# TESTING

def test_model(model, test_loader, test_case_ids=None, device="cpu"):
    """
    Uses the trained model to make predictions on the test data.

    The predictions and targets are still scaled.
    Use the scaler to convert them back to normal elongation units.

    Keep shuffle=False in the test DataLoader so predictions stay
    matched with the correct case IDs.

    Returns:
        preds: model predictions
        targets: correct target values
        case_ids: IDs connected to the test samples
    """

    # Move the model to the CPU or GPU
    model.to(device)

    # Put the model in evaluation mode
    model.eval()

    # Store predictions and correct answers
    all_preds = []
    all_targets = []

    # Gradients are not needed during testing
    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            # Move inputs to the CPU or GPU
            X_batch = X_batch.to(device)

            # Make predictions
            preds = model(X_batch)

            # Move predictions back to the CPU and save them
            all_preds.append(preds.cpu())

            # Save the correct target values
            all_targets.append(y_batch)

    # Join all batches into complete tensors
    preds = torch.cat(all_preds)
    targets = torch.cat(all_targets)

    # Make sure every prediction has a matching case ID
    if test_case_ids is not None and len(test_case_ids) != len(preds):
        raise ValueError(
            f"Number of case IDs ({len(test_case_ids)}) does not match "
            f"number of predictions ({len(preds)}). Make sure the test "
            f"DataLoader uses shuffle=False."
        )

    return preds, targets, test_case_ids

# PLOTTING


def plot_loss(history, save_path=None):
   
    train_loss = history["train_loss"]
    val_loss = history["val_loss"]

    epochs = range(1, len(train_loss) + 1)

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, train_loss, label="Training Loss")
    plt.plot(epochs, val_loss, label="Validation Loss")
    plt.xlabel("Epoch")
    plt.ylabel("MSE Loss")
    plt.title("Training and Validation Loss")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path)
    plt.show()
    plt.close()



# METRICS


def compute_metrics(preds, targets, scaler=None, features_to_scale=None, target_col="Elongation", print_results=True):

    if isinstance(preds, torch.Tensor):
        preds = preds.detach().cpu().numpy()
    if isinstance(targets, torch.Tensor):
        targets = targets.detach().cpu().numpy()

    preds = np.asarray(preds).reshape(-1)
    targets = np.asarray(targets).reshape(-1)

    if scaler is not None:
        if features_to_scale is None:
            raise ValueError("features_to_scale is required to inverse-transform with the scaler.")
        target_index = features_to_scale.index(target_col)
        mean = scaler.mean_[target_index]
        scale = scaler.scale_[target_index]
        preds_original = preds * scale + mean
        targets_original = targets * scale + mean
    else:
        preds_original = preds
        targets_original = targets

    mae = mean_absolute_error(targets_original, preds_original)
    rmse = np.sqrt(mean_squared_error(targets_original, preds_original))
    r2 = r2_score(targets_original, preds_original)

    metrics = {"MAE": mae, "RMSE": rmse, "R2": r2}

    if print_results:
        print(f"MAE:  {mae:.4f}")
        print(f"RMSE: {rmse:.4f}")
        print(f"R²:   {r2:.4f}")

    return metrics, preds_original, targets_original
